name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: vitoriediezc
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=ff8fab&color_dots=#ffc8dd,#ffb4a2,#ff8fab,#fb6f92,#cdb4db

      - name: Push snake
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist"
          message: "update snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
